ARG BUILDER
FROM alpine:latest
WORKDIR /root/

#TODO AW: find where it will be built and copy from there
COPY --from=${BUILDER} /app_src/bin/rank_collector .

# Expose port (for your HTTP server)
EXPOSE 50051

# Run the app
CMD ["./rank_collector"]
